// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyPlayer.Persistence;

namespace MonkeyPlayer.Persistence.Migrations
{
    [DbContext(typeof(MonkeyPlayerDataContext))]
    partial class MonkeyPlayerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MonkeyPlayer.Domain.Song.SongEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SongInBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StyleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Songs", "player");
                });
#pragma warning restore 612, 618
        }
    }
}
